# poliz config options
autosave_enabled=true
autosave_interval_seconds=60
default_directory=poliz_data
clients_filename=clients.csv
policies_filename=policies.csv
interactions_filename=interactions.csv
